In [91]:
import pandas as pd

In [92]:
# Import both CSVs. Convert all date columns to datetime. 
# Check for missing values in the visits data. 
# Fill missing Insurance_Covered with the median Insurance_Covered for that specific Department using .transform(). 
# Fill missing Wait_Time_Min with the average Wait_Time_Min for that specific Doctor_ID using .transform(). 
# Verify no nulls remain.

patients = pd.read_csv('hospital_visits.csv')
patients['Visit_Date'] = pd.to_datetime(patients['Visit_Date'])
patients.isnull().sum()
patients['Insurance_Covered'] = patients['Insurance_Covered'].fillna(patients.groupby('Department')['Insurance_Covered'].transform('median'))
patients['Wait_Time_Min'] = patients['Wait_Time_Min'].fillna(patients.groupby('Doctor_ID')['Wait_Time_Min'].transform('mean'))
patients.isnull().sum()
patients

,Visit_ID,Patient_ID,Doctor_ID,Department,Visit_Date,Diagnosis,Treatment_Cost,Insurance_Covered,Follow_Up_Required,Wait_Time_Min
0,V001,P101,D01,Cardiology,2024-01-03,Heart Murmur,1500.0,1200.0,Yes,35.00
1,V002,P102,D02,Orthopedics,2024-01-05,Fracture,2200.0,1750.0,Yes,50.00
2,V003,P101,D01,Cardiology,2024-01-10,Heart Murmur,1600.0,1300.0,Yes,28.00
3,V004,P103,D03,Neurology,2024-01-12,Migraine,800.0,600.0,No,42.00
4,V005,P104,D02,Orthopedics,2024-01-15,Sprain,650.0,500.0,No,65.00
5,V006,P105,D01,Cardiology,2024-01-18,Arrhythmia,3200.0,2400.0,Yes,30.00
6,V007,P102,D03,Neurology,2024-01-20,Concussion,1800.0,1400.0,Yes,55.00
7,V008,P106,D02,Orthopedics,2024-01-22,Fracture,2400.0,1800.0,No,58.75
8,V009,P101,D01,Cardiology,2024-01-25,Heart Murmur,1550.0,1825.0,Yes,32.00
9,V010,P107,D03,Neurology,2024-01-28,Migraine,850.0,650.0,No,48.00
10,V011,P103,D01,Cardiology,2024-02-01,Arrhythmia,3100.0,2300.0,Yes,30.00
11,V012,P108,D02,Orthopedics,2024-02-03,Sprain,700.0,550.0,No,58.00
12,V013,P104,D03,Neurology,2024-02-05,Migraine,900.0,675.0,Yes,40.00
13,V014,P101,D01,Cardiology,2024-02-08,Heart Murmur,1650.0,1350.0,No,25.00
14,V015,P109,D02,Orthopedics,2024-02-10,Fracture,2500.0,1900.0,Yes,58.75
15,V016,P105,D03,Neurology,2024-02-12,Concussion,1900.0,1500.0,Yes,52.00
16,V017,P110,D01,Cardiology,2024-02-15,Arrhythmia,3300.0,2500.0,Yes,29.00
17,V018,P102,D02,Orthopedics,2024-02-18,Fracture,2350.0,1750.0,No,62.00
18,V019,P111,D03,Neurology,2024-02-20,Migraine,875.0,675.0,No,45.00
19,V020,P103,D01,Cardiology,2024-02-22,Heart Murmur,1700.0,1825.0,Yes,31.00

In [93]:
doctors = pd.read_csv('doctors.csv')
doctors['Hire_Date'] = pd.to_datetime(doctors['Hire_Date'])
doctors

  Doctor_ID Doctor_Name    Specialty  Years_Experience  Hire_Date
0       D01   Dr. Patel   Cardiology                15 2009-06-01
1       D02     Dr. Kim  Orthopedics                 8 2016-03-15
2       D03  Dr. Santos    Neurology                12 2012-09-20
3       D04    Dr. Chen  Dermatology                 5 2019-11-01

In [94]:
# Inner join the visits with the doctors data on Doctor_ID. 
# Then do a left join on the same data. 
# Compare the row counts — identify which transactions exist in the left join but not the inner join and explain why. 
# Create a column Doctor_Matched using .notna().

patdocinner = patients.merge(doctors, on = 'Doctor_ID', how = 'left')
patdocinner.shape[0]
patdocinner.shape[1]
patdocinner['Doctor_Matched'] = patdocinner['Doctor_Name'].notna()
patdocinner

,Visit_ID,Patient_ID,Doctor_ID,Department,Visit_Date,Diagnosis,Treatment_Cost,Insurance_Covered,Follow_Up_Required,Wait_Time_Min,Doctor_Name,Specialty,Years_Experience,Hire_Date,Doctor_Matched
0,V001,P101,D01,Cardiology,2024-01-03,Heart Murmur,1500.0,1200.0,Yes,35.00,Dr. Patel,Cardiology,15,2009-06-01,True
1,V002,P102,D02,Orthopedics,2024-01-05,Fracture,2200.0,1750.0,Yes,50.00,Dr. Kim,Orthopedics,8,2016-03-15,True
2,V003,P101,D01,Cardiology,2024-01-10,Heart Murmur,1600.0,1300.0,Yes,28.00,Dr. Patel,Cardiology,15,2009-06-01,True
3,V004,P103,D03,Neurology,2024-01-12,Migraine,800.0,600.0,No,42.00,Dr. Santos,Neurology,12,2012-09-20,True
4,V005,P104,D02,Orthopedics,2024-01-15,Sprain,650.0,500.0,No,65.00,Dr. Kim,Orthopedics,8,2016-03-15,True
5,V006,P105,D01,Cardiology,2024-01-18,Arrhythmia,3200.0,2400.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True
6,V007,P102,D03,Neurology,2024-01-20,Concussion,1800.0,1400.0,Yes,55.00,Dr. Santos,Neurology,12,2012-09-20,True
7,V008,P106,D02,Orthopedics,2024-01-22,Fracture,2400.0,1800.0,No,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True
8,V009,P101,D01,Cardiology,2024-01-25,Heart Murmur,1550.0,1825.0,Yes,32.00,Dr. Patel,Cardiology,15,2009-06-01,True
9,V010,P107,D03,Neurology,2024-01-28,Migraine,850.0,650.0,No,48.00,Dr. Santos,Neurology,12,2012-09-20,True
10,V011,P103,D01,Cardiology,2024-02-01,Arrhythmia,3100.0,2300.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True
11,V012,P108,D02,Orthopedics,2024-02-03,Sprain,700.0,550.0,No,58.00,Dr. Kim,Orthopedics,8,2016-03-15,True
12,V013,P104,D03,Neurology,2024-02-05,Migraine,900.0,675.0,Yes,40.00,Dr. Santos,Neurology,12,2012-09-20,True
13,V014,P101,D01,Cardiology,2024-02-08,Heart Murmur,1650.0,1350.0,No,25.00,Dr. Patel,Cardiology,15,2009-06-01,True
14,V015,P109,D02,Orthopedics,2024-02-10,Fracture,2500.0,1900.0,Yes,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True
15,V016,P105,D03,Neurology,2024-02-12,Concussion,1900.0,1500.0,Yes,52.00,Dr. Santos,Neurology,12,2012-09-20,True
16,V017,P110,D01,Cardiology,2024-02-15,Arrhythmia,3300.0,2500.0,Yes,29.00,Dr. Patel,Cardiology,15,2009-06-01,True
17,V018,P102,D02,Orthopedics,2024-02-18,Fracture,2350.0,1750.0,No,62.00,Dr. Kim,Orthopedics,8,2016-03-15,True
18,V019,P111,D03,Neurology,2024-02-20,Migraine,875.0,675.0,No,45.00,Dr. Santos,Neurology,12,2012-09-20,True
19,V020,P103,D01,Cardiology,2024-02-22,Heart Murmur,1700.0,1825.0,Yes,31.00,Dr. Patel,Cardiology,15,2009-06-01,True

In [95]:
patdocleft = patients.merge(doctors, on = 'Doctor_ID', how = 'left')
patdocleft.shape[0]
patdocleft.shape[1]
patdocleft['Doctor_Matched'] = patdocleft['Doctor_Name'].notna()
patdocleft

,Visit_ID,Patient_ID,Doctor_ID,Department,Visit_Date,Diagnosis,Treatment_Cost,Insurance_Covered,Follow_Up_Required,Wait_Time_Min,Doctor_Name,Specialty,Years_Experience,Hire_Date,Doctor_Matched
0,V001,P101,D01,Cardiology,2024-01-03,Heart Murmur,1500.0,1200.0,Yes,35.00,Dr. Patel,Cardiology,15,2009-06-01,True
1,V002,P102,D02,Orthopedics,2024-01-05,Fracture,2200.0,1750.0,Yes,50.00,Dr. Kim,Orthopedics,8,2016-03-15,True
2,V003,P101,D01,Cardiology,2024-01-10,Heart Murmur,1600.0,1300.0,Yes,28.00,Dr. Patel,Cardiology,15,2009-06-01,True
3,V004,P103,D03,Neurology,2024-01-12,Migraine,800.0,600.0,No,42.00,Dr. Santos,Neurology,12,2012-09-20,True
4,V005,P104,D02,Orthopedics,2024-01-15,Sprain,650.0,500.0,No,65.00,Dr. Kim,Orthopedics,8,2016-03-15,True
5,V006,P105,D01,Cardiology,2024-01-18,Arrhythmia,3200.0,2400.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True
6,V007,P102,D03,Neurology,2024-01-20,Concussion,1800.0,1400.0,Yes,55.00,Dr. Santos,Neurology,12,2012-09-20,True
7,V008,P106,D02,Orthopedics,2024-01-22,Fracture,2400.0,1800.0,No,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True
8,V009,P101,D01,Cardiology,2024-01-25,Heart Murmur,1550.0,1825.0,Yes,32.00,Dr. Patel,Cardiology,15,2009-06-01,True
9,V010,P107,D03,Neurology,2024-01-28,Migraine,850.0,650.0,No,48.00,Dr. Santos,Neurology,12,2012-09-20,True
10,V011,P103,D01,Cardiology,2024-02-01,Arrhythmia,3100.0,2300.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True
11,V012,P108,D02,Orthopedics,2024-02-03,Sprain,700.0,550.0,No,58.00,Dr. Kim,Orthopedics,8,2016-03-15,True
12,V013,P104,D03,Neurology,2024-02-05,Migraine,900.0,675.0,Yes,40.00,Dr. Santos,Neurology,12,2012-09-20,True
13,V014,P101,D01,Cardiology,2024-02-08,Heart Murmur,1650.0,1350.0,No,25.00,Dr. Patel,Cardiology,15,2009-06-01,True
14,V015,P109,D02,Orthopedics,2024-02-10,Fracture,2500.0,1900.0,Yes,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True
15,V016,P105,D03,Neurology,2024-02-12,Concussion,1900.0,1500.0,Yes,52.00,Dr. Santos,Neurology,12,2012-09-20,True
16,V017,P110,D01,Cardiology,2024-02-15,Arrhythmia,3300.0,2500.0,Yes,29.00,Dr. Patel,Cardiology,15,2009-06-01,True
17,V018,P102,D02,Orthopedics,2024-02-18,Fracture,2350.0,1750.0,No,62.00,Dr. Kim,Orthopedics,8,2016-03-15,True
18,V019,P111,D03,Neurology,2024-02-20,Migraine,875.0,675.0,No,45.00,Dr. Santos,Neurology,12,2012-09-20,True
19,V020,P103,D01,Cardiology,2024-02-22,Heart Murmur,1700.0,1825.0,Yes,31.00,Dr. Patel,Cardiology,15,2009-06-01,True

In [96]:
# Create columns for Out_Of_Pocket (Treatment_Cost - Insurance_Covered), and Cost_Ratio (Insurance_Covered / Treatment_Cost). 
# Convert Follow_Up_Required to boolean. 
# Then create a pivot table showing the average Out_Of_Pocket by Department (rows) and Follow_Up_Required (columns) with margins. 
# For each Department, calculate the cumulative Treatment_Cost ordered by Visit_Date. Also calculate the visit-over-visit percentage change in Treatment_Cost per Department using .shift().

patdoc = patdocleft.copy()
patdoc['Out_Of_Pocket'] = patdoc['Treatment_Cost'] - patdoc['Insurance_Covered']
patdoc['Cost_Ratio'] = (patdoc['Insurance_Covered'] / patdoc['Treatment_Cost']).round(2)
pt = pd.pivot_table(patdoc, values = 'Out_Of_Pocket', index = 'Department', columns = 'Follow_Up_Required', aggfunc = 'mean', fill_value = 0, margins = True).round(2)
pt

patdoc = patdoc.sort_values('Visit_Date')
patdoc['Cumulative_Treatment_Cost'] = patdoc.groupby('Department')['Treatment_Cost'].cumsum()
patdoc['Visit_Percent_Change'] = (patdoc['Treatment_Cost'] / (patdoc.groupby('Department')['Treatment_Cost'].shift(1)) * 100).round(2)
patdoc

,Visit_ID,Patient_ID,Doctor_ID,Department,Visit_Date,Diagnosis,Treatment_Cost,Insurance_Covered,Follow_Up_Required,Wait_Time_Min,Doctor_Name,Specialty,Years_Experience,Hire_Date,Doctor_Matched,Out_Of_Pocket,Cost_Ratio,Cumulative_Treatment_Cost,Visit_Percent_Change
0,V001,P101,D01,Cardiology,2024-01-03,Heart Murmur,1500.0,1200.0,Yes,35.00,Dr. Patel,Cardiology,15,2009-06-01,True,300.0,0.80,1500.0,NaN
1,V002,P102,D02,Orthopedics,2024-01-05,Fracture,2200.0,1750.0,Yes,50.00,Dr. Kim,Orthopedics,8,2016-03-15,True,450.0,0.80,2200.0,NaN
2,V003,P101,D01,Cardiology,2024-01-10,Heart Murmur,1600.0,1300.0,Yes,28.00,Dr. Patel,Cardiology,15,2009-06-01,True,300.0,0.81,3100.0,106.67
3,V004,P103,D03,Neurology,2024-01-12,Migraine,800.0,600.0,No,42.00,Dr. Santos,Neurology,12,2012-09-20,True,200.0,0.75,800.0,NaN
4,V005,P104,D02,Orthopedics,2024-01-15,Sprain,650.0,500.0,No,65.00,Dr. Kim,Orthopedics,8,2016-03-15,True,150.0,0.77,2850.0,29.55
5,V006,P105,D01,Cardiology,2024-01-18,Arrhythmia,3200.0,2400.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True,800.0,0.75,6300.0,200.00
6,V007,P102,D03,Neurology,2024-01-20,Concussion,1800.0,1400.0,Yes,55.00,Dr. Santos,Neurology,12,2012-09-20,True,400.0,0.78,2600.0,225.00
7,V008,P106,D02,Orthopedics,2024-01-22,Fracture,2400.0,1800.0,No,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True,600.0,0.75,5250.0,369.23
8,V009,P101,D01,Cardiology,2024-01-25,Heart Murmur,1550.0,1825.0,Yes,32.00,Dr. Patel,Cardiology,15,2009-06-01,True,-275.0,1.18,7850.0,48.44
9,V010,P107,D03,Neurology,2024-01-28,Migraine,850.0,650.0,No,48.00,Dr. Santos,Neurology,12,2012-09-20,True,200.0,0.76,3450.0,47.22
10,V011,P103,D01,Cardiology,2024-02-01,Arrhythmia,3100.0,2300.0,Yes,30.00,Dr. Patel,Cardiology,15,2009-06-01,True,800.0,0.74,10950.0,200.00
11,V012,P108,D02,Orthopedics,2024-02-03,Sprain,700.0,550.0,No,58.00,Dr. Kim,Orthopedics,8,2016-03-15,True,150.0,0.79,5950.0,29.17
12,V013,P104,D03,Neurology,2024-02-05,Migraine,900.0,675.0,Yes,40.00,Dr. Santos,Neurology,12,2012-09-20,True,225.0,0.75,4350.0,105.88
13,V014,P101,D01,Cardiology,2024-02-08,Heart Murmur,1650.0,1350.0,No,25.00,Dr. Patel,Cardiology,15,2009-06-01,True,300.0,0.82,12600.0,53.23
14,V015,P109,D02,Orthopedics,2024-02-10,Fracture,2500.0,1900.0,Yes,58.75,Dr. Kim,Orthopedics,8,2016-03-15,True,600.0,0.76,8450.0,357.14
15,V016,P105,D03,Neurology,2024-02-12,Concussion,1900.0,1500.0,Yes,52.00,Dr. Santos,Neurology,12,2012-09-20,True,400.0,0.79,6250.0,211.11
16,V017,P110,D01,Cardiology,2024-02-15,Arrhythmia,3300.0,2500.0,Yes,29.00,Dr. Patel,Cardiology,15,2009-06-01,True,800.0,0.76,15900.0,200.00
17,V018,P102,D02,Orthopedics,2024-02-18,Fracture,2350.0,1750.0,No,62.00,Dr. Kim,Orthopedics,8,2016-03-15,True,600.0,0.74,10800.0,94.00
18,V019,P111,D03,Neurology,2024-02-20,Migraine,875.0,675.0,No,45.00,Dr. Santos,Neurology,12,2012-09-20,True,200.0,0.77,7125.0,46.05
19,V020,P103,D01,Cardiology,2024-02-22,Heart Murmur,1700.0,1825.0,Yes,31.00,Dr. Patel,Cardiology,15,2009-06-01,True,-125.0,1.07,17600.0,51.52

In [97]:
# Using .agg() with named aggregations, calculate per Doctor: total Treatment_Cost, average Wait_Time_Min, number of unique patients (nunique), and follow-up rate (mean of the boolean Follow_Up_Required). 
# Rank doctors by total Treatment_Cost descending. Use .map() with a dictionary to label doctors with total Treatment_Cost > 10000 as 'High Volume' and others as 'Standard'.

patdoc['Follow_Up_Required'] = patdoc['Follow_Up_Required'].apply(lambda x: True if x == 'Yes' else False)
doctor_stats = patdoc.groupby('Doctor_ID').agg(Total_Treatment_Cost = ('Treatment_Cost', 'sum'), Avergae_Wait = ('Wait_Time_Min', 'mean'), Unique_Patients = ('Patient_ID', 'nunique'), Follow_Up_Rate = ('Follow_Up_Required', 'mean'))
doctor_stats['Rank'] = doctor_stats['Total_Treatment_Cost'].rank(ascending = False).astype(int)
performance_dict = {doctor: 'High Volume' if cost > 10000 else 'Standard' for doctor, cost in doctor_stats['Total_Treatment_Cost'].items()}
doctor_stats['Performance'] = doctor_stats.index.map(performance_dict)
doctor_stats

,Total_Treatment_Cost,Avergae_Wait,Unique_Patients,Follow_Up_Rate,Rank,Performance
Doctor_ID,,,,,,
D01,17600.0,30.00,4,0.875000,1,High Volume
D02,10800.0,58.75,5,0.333333,2,High Volume
D03,7125.0,47.00,6,0.500000,3,Standard

In [98]:
# Identify repeat patients (more than one visit) using boolean indexing on grouped results. 
# For repeat patients only, find each one's most common Diagnosis using .drop_duplicates() after sorting. 
# Calculate their average Out_Of_Pocket and total visits. 
# Find which repeat patient has the highest cumulative Treatment_Cost using .idxmax(). 
# Display everything using a nested lambda to label patients: 'Frequent' if visits > 3, 'Returning' if 2-3 visits.

patient_stats = patdoc.groupby('Patient_ID').size().reset_index(name = 'Number_of_Visits')
patient_stats = patient_stats[patient_stats['Number_of_Visits'] > 1]

diagnosis_count = patdoc.groupby(['Patient_ID', 'Diagnosis']).size().reset_index(name = 'Diagnosis_Count')
top_diagnosis = diagnosis_count.sort_values('Diagnosis_Count', ascending=False)
top_diagnosis = top_diagnosis.drop_duplicates(subset='Patient_ID')
top_diagnosis

repeat_oop = (patdoc[patdoc['Patient_ID'].isin(patient_stats['Patient_ID'])].groupby('Patient_ID')['Out_Of_Pocket'].mean().reset_index(name='Avg_Out_Of_Pocket')).round(2)

final = patient_stats.merge(top_diagnosis[['Patient_ID', 'Diagnosis']], on='Patient_ID')
final = final.merge(repeat_oop, on='Patient_ID')

pctc = patdoc[patdoc['Patient_ID'].isin(patient_stats['Patient_ID'])].groupby('Patient_ID')['Treatment_Cost'].sum().reset_index(name='Total_Treatment_Cost')
final = final.merge(pctc, on = 'Patient_ID')
final = final.sort_values('Total_Treatment_Cost', ascending = False)
expensive = final.loc[final['Total_Treatment_Cost'].idxmax(), 'Patient_ID']
print(f"The patient with the highest cumulative treatment costs is: {expensive}")

final['Patient_Visit_Rating'] = final['Number_of_Visits'].apply(lambda x: 'Frequent' if x > 3 else ('Returning' if x >= 2 else ('Not Frequent' if x == 1 else 'Non-existent')))
final

The patient with the highest cumulative treatment costs is: P102

,Patient_ID,Number_of_Visits,Diagnosis,Avg_Out_Of_Pocket,Total_Treatment_Cost,Patient_Visit_Rating
1,P102,3,Fracture,483.33,6350.0,Returning
0,P101,4,Heart Murmur,156.25,6300.0,Frequent
2,P103,3,Arrhythmia,291.67,5600.0,Returning
4,P105,2,Arrhythmia,600.00,5100.0,Returning
3,P104,2,Migraine,187.50,1550.0,Returning