In [1]:
import pandas as pd

In [2]:
# Import the CSV, convert Start_Date to datetime, and create a column called Tenure_Days that calculates how many days each rep has been with the company as of 2024-12-31.
df = pd.read_csv('sales_reps.csv')
df['Start_Date'] = pd.to_datetime(df['Start_Date'])
df['Tenure_Days'] = (pd.to_datetime('2024-12-31') - df['Start_Date']).dt.days
df

,Rep_ID,Rep_Name,Manager,Region,Quarter,Product,Revenue,Deals_Closed,Deals_Lost,Start_Date,Tenure_Days
0,R001,Anna,James,North,Q1,Software,85000,12,3,2022-06-15,930
1,R001,Anna,James,North,Q2,Software,92000,15,2,2022-06-15,930
2,R001,Anna,James,North,Q3,Software,78000,10,5,2022-06-15,930
3,R001,Anna,James,North,Q4,Software,105000,18,1,2022-06-15,930
4,R002,Brian,James,North,Q1,Hardware,64000,8,6,2023-01-10,721
5,R002,Brian,James,North,Q2,Hardware,71000,10,4,2023-01-10,721
6,R002,Brian,James,North,Q3,Hardware,58000,7,7,2023-01-10,721
7,R002,Brian,James,North,Q4,Hardware,82000,13,3,2023-01-10,721
8,R003,Carla,Susan,South,Q1,Software,95000,14,2,2021-03-22,1380
9,R003,Carla,Susan,South,Q2,Software,88000,12,4,2021-03-22,1380
10,R003,Carla,Susan,South,Q3,Software,102000,16,1,2021-03-22,1380
11,R003,Carla,Susan,South,Q4,Software,97000,15,3,2021-03-22,1380
12,R004,Derek,Susan,South,Q1,Hardware,73000,9,5,2023-08-01,518
13,R004,Derek,Susan,South,Q2,Hardware,69000,8,6,2023-08-01,518
14,R004,Derek,Susan,South,Q3,Hardware,75000,11,4,2023-08-01,518
15,R004,Derek,Susan,South,Q4,Hardware,81000,12,2,2023-08-01,518
16,R005,Elena,James,North,Q1,Software,110000,20,1,2020-11-05,1517
17,R005,Elena,James,North,Q2,Software,98000,16,3,2020-11-05,1517
18,R005,Elena,James,North,Q3,Software,87000,13,4,2020-11-05,1517
19,R005,Elena,James,North,Q4,Software,115000,21,2,2020-11-05,1517
20,R006,Frank,Susan,South,Q1,Hardware,55000,7,8,2024-01-15,351
21,R006,Frank,Susan,South,Q2,Hardware,62000,9,5,2024-01-15,351
22,R006,Frank,Susan,South,Q3,Hardware,48000,6,9,2024-01-15,351
23,R006,Frank,Susan,South,Q4,Hardware,70000,10,4,2024-01-15,351

In [3]:
# Create a column called Win_Rate calculated as Deals_Closed / (Deals_Closed + Deals_Lost). Then create a Win_Rate_Label using a lambda: 'Strong' if Win_Rate > 0.7, 'Average' if between 0.5 and 0.7 inclusive, 'Weak' if below 0.5.
df['Win_Rate'] = (df['Deals_Closed'] / (df['Deals_Closed'] + df['Deals_Lost'])).round(2)
df['Win_Rate_Label'] = df['Win_Rate'].apply(lambda x: 'Strong' if x > 0.7 else ('Weak' if x < 0.5 else 'Average'))
df

,Rep_ID,Rep_Name,Manager,Region,Quarter,Product,Revenue,Deals_Closed,Deals_Lost,Start_Date,Tenure_Days,Win_Rate,Win_Rate_Label
0,R001,Anna,James,North,Q1,Software,85000,12,3,2022-06-15,930,0.80,Strong
1,R001,Anna,James,North,Q2,Software,92000,15,2,2022-06-15,930,0.88,Strong
2,R001,Anna,James,North,Q3,Software,78000,10,5,2022-06-15,930,0.67,Average
3,R001,Anna,James,North,Q4,Software,105000,18,1,2022-06-15,930,0.95,Strong
4,R002,Brian,James,North,Q1,Hardware,64000,8,6,2023-01-10,721,0.57,Average
5,R002,Brian,James,North,Q2,Hardware,71000,10,4,2023-01-10,721,0.71,Strong
6,R002,Brian,James,North,Q3,Hardware,58000,7,7,2023-01-10,721,0.50,Average
7,R002,Brian,James,North,Q4,Hardware,82000,13,3,2023-01-10,721,0.81,Strong
8,R003,Carla,Susan,South,Q1,Software,95000,14,2,2021-03-22,1380,0.88,Strong
9,R003,Carla,Susan,South,Q2,Software,88000,12,4,2021-03-22,1380,0.75,Strong
10,R003,Carla,Susan,South,Q3,Software,102000,16,1,2021-03-22,1380,0.94,Strong
11,R003,Carla,Susan,South,Q4,Software,97000,15,3,2021-03-22,1380,0.83,Strong
12,R004,Derek,Susan,South,Q1,Hardware,73000,9,5,2023-08-01,518,0.64,Average
13,R004,Derek,Susan,South,Q2,Hardware,69000,8,6,2023-08-01,518,0.57,Average
14,R004,Derek,Susan,South,Q3,Hardware,75000,11,4,2023-08-01,518,0.73,Strong
15,R004,Derek,Susan,South,Q4,Hardware,81000,12,2,2023-08-01,518,0.86,Strong
16,R005,Elena,James,North,Q1,Software,110000,20,1,2020-11-05,1517,0.95,Strong
17,R005,Elena,James,North,Q2,Software,98000,16,3,2020-11-05,1517,0.84,Strong
18,R005,Elena,James,North,Q3,Software,87000,13,4,2020-11-05,1517,0.76,Strong
19,R005,Elena,James,North,Q4,Software,115000,21,2,2020-11-05,1517,0.91,Strong
20,R006,Frank,Susan,South,Q1,Hardware,55000,7,8,2024-01-15,351,0.47,Weak
21,R006,Frank,Susan,South,Q2,Hardware,62000,9,5,2024-01-15,351,0.64,Average
22,R006,Frank,Susan,South,Q3,Hardware,48000,6,9,2024-01-15,351,0.40,Weak
23,R006,Frank,Susan,South,Q4,Hardware,70000,10,4,2024-01-15,351,0.71,Strong

In [4]:
# Create a column called Revenue_Change that shows the quarter-over-quarter percentage change in Revenue for each rep. Q1 should show NaN since there's no prior quarter. The formula is ((Current - Previous) / Previous) * 100.
df['Revenue_Change'] = ((df['Revenue'] - df.groupby('Rep_ID')['Revenue'].shift(1)) / (df.groupby('Rep_ID')['Revenue'].shift(1)) * 100).round(2)
df

,Rep_ID,Rep_Name,Manager,Region,Quarter,Product,Revenue,Deals_Closed,Deals_Lost,Start_Date,Tenure_Days,Win_Rate,Win_Rate_Label,Revenue_Change
0,R001,Anna,James,North,Q1,Software,85000,12,3,2022-06-15,930,0.80,Strong,NaN
1,R001,Anna,James,North,Q2,Software,92000,15,2,2022-06-15,930,0.88,Strong,8.24
2,R001,Anna,James,North,Q3,Software,78000,10,5,2022-06-15,930,0.67,Average,-15.22
3,R001,Anna,James,North,Q4,Software,105000,18,1,2022-06-15,930,0.95,Strong,34.62
4,R002,Brian,James,North,Q1,Hardware,64000,8,6,2023-01-10,721,0.57,Average,NaN
5,R002,Brian,James,North,Q2,Hardware,71000,10,4,2023-01-10,721,0.71,Strong,10.94
6,R002,Brian,James,North,Q3,Hardware,58000,7,7,2023-01-10,721,0.50,Average,-18.31
7,R002,Brian,James,North,Q4,Hardware,82000,13,3,2023-01-10,721,0.81,Strong,41.38
8,R003,Carla,Susan,South,Q1,Software,95000,14,2,2021-03-22,1380,0.88,Strong,NaN
9,R003,Carla,Susan,South,Q2,Software,88000,12,4,2021-03-22,1380,0.75,Strong,-7.37
10,R003,Carla,Susan,South,Q3,Software,102000,16,1,2021-03-22,1380,0.94,Strong,15.91
11,R003,Carla,Susan,South,Q4,Software,97000,15,3,2021-03-22,1380,0.83,Strong,-4.90
12,R004,Derek,Susan,South,Q1,Hardware,73000,9,5,2023-08-01,518,0.64,Average,NaN
13,R004,Derek,Susan,South,Q2,Hardware,69000,8,6,2023-08-01,518,0.57,Average,-5.48
14,R004,Derek,Susan,South,Q3,Hardware,75000,11,4,2023-08-01,518,0.73,Strong,8.70
15,R004,Derek,Susan,South,Q4,Hardware,81000,12,2,2023-08-01,518,0.86,Strong,8.00
16,R005,Elena,James,North,Q1,Software,110000,20,1,2020-11-05,1517,0.95,Strong,NaN
17,R005,Elena,James,North,Q2,Software,98000,16,3,2020-11-05,1517,0.84,Strong,-10.91
18,R005,Elena,James,North,Q3,Software,87000,13,4,2020-11-05,1517,0.76,Strong,-11.22
19,R005,Elena,James,North,Q4,Software,115000,21,2,2020-11-05,1517,0.91,Strong,32.18
20,R006,Frank,Susan,South,Q1,Hardware,55000,7,8,2024-01-15,351,0.47,Weak,NaN
21,R006,Frank,Susan,South,Q2,Hardware,62000,9,5,2024-01-15,351,0.64,Average,12.73
22,R006,Frank,Susan,South,Q3,Hardware,48000,6,9,2024-01-15,351,0.40,Weak,-22.58
23,R006,Frank,Susan,South,Q4,Hardware,70000,10,4,2024-01-15,351,0.71,Strong,45.83

In [5]:
# For each Manager, calculate the total Revenue, average Win_Rate, and total Deals_Closed across all their reps. Display sorted by total Revenue descending.
#x = df.groupby('Manager')['Revenue'].sum()
#y = df.groupby('Manager')['Win_Rate'].mean()
#z = df.groupby('Manager')['Deals_Closed'].sum()

#result = pd.DataFrame({'Manager_Total_Rev' : x, 'Manager_Win_Avg' : y, 'Manager_Deals_Closed' : z})
#result = result.sort_values('Manager_Total_Rev', ascending=False)

#result = x.merge(y, on='Manager').merge(z, on='Manager')
#result.sort_values('Manager_Total_Rev', ascending=False)

result = df.groupby('Manager').agg(Manager_Total_Rev=('Revenue', 'sum'), Manager_Win_Avg=('Win_Rate', 'mean'), Manager_Deals_Closed=('Deals_Closed', 'sum')).reset_index().sort_values('Manager_Total_Rev', ascending=False)
result

  Manager  Manager_Total_Rev  Manager_Win_Avg  Manager_Deals_Closed
0   James            1045000         0.779167                   163
1   Susan             915000         0.701667                   129

In [6]:
# Rank each rep by their total annual Revenue (sum across all quarters) and display the ranking with rep name and total revenue. Rank 1 = highest revenue.
rep_rank = df.groupby('Rep_Name')['Revenue'].sum().reset_index(name='Total_Revenue')
rep_rank['Rank'] = rep_rank['Total_Revenue'].rank(ascending=False).astype(int)
rep_rank = rep_rank.sort_values('Rank')
rep_rank

  Rep_Name  Total_Revenue  Rank
4    Elena         410000     1
2    Carla         382000     2
0     Anna         360000     3
3    Derek         298000     4
1    Brian         275000     5
5    Frank         235000     6