In [1]:
import pandas as pd

In [2]:
# Import the CSV and convert Transaction_Date to a proper datetime type.
df = pd.read_csv('transactions.csv')
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

# Create a column called Transaction_Type — label it 'Purchase' if Amount is positive, 'Return' if negative. Use a lambda.
df['Transaction_Type'] = df['Amount'].apply(lambda x: 'Purchase' if x > 0 else 'Return')
df

,Transaction_ID,Customer_ID,Transaction_Date,Amount,Category,Transaction_Type
0,1001,C001,2024-01-05,250.0,Electronics,Purchase
1,1002,C001,2024-01-12,75.0,Groceries,Purchase
2,1003,C002,2024-01-08,-50.0,Electronics,Return
3,1004,C001,2024-01-20,300.0,Electronics,Purchase
4,1005,C003,2024-01-15,120.0,Clothing,Purchase
5,1006,C002,2024-01-22,200.0,Groceries,Purchase
6,1007,C003,2024-01-25,-30.0,Clothing,Return
7,1008,C001,2024-02-01,500.0,Electronics,Purchase
8,1009,C002,2024-02-05,150.0,Electronics,Purchase
9,1010,C003,2024-02-10,80.0,Groceries,Purchase
10,1011,C001,2024-02-15,-100.0,Electronics,Return
11,1012,C002,2024-02-18,175.0,Clothing,Purchase
12,1013,C003,2024-02-22,90.0,Clothing,Purchase
13,1014,C001,2024-02-28,425.0,Groceries,Purchase
14,1015,C003,2024-03-01,-25.0,Electronics,Return

In [3]:
# For each Customer_ID, calculate their total spend (sum of all positive amounts only), total returns (sum of all negative amounts only), 
# and net spend (total of everything). Display this as a single grouped DataFrame sorted by net spend descending.
total_spend = df[df['Amount'] > 0].groupby('Customer_ID')['Amount'].sum()
total_returns = df[df['Amount'] < 0].groupby('Customer_ID')['Amount'].sum()
net_spend = df.groupby('Customer_ID')['Amount'].sum()

result = pd.DataFrame({'Total_Spend' : total_spend, 'Total_Returns' : total_returns, 'Net_Spend' : net_spend})
result.sort_values('Net_Spend', ascending=False)

             Total_Spend  Total_Returns  Net_Spend
Customer_ID
C001              1550.0         -100.0     1450.0
C002               525.0          -50.0      475.0
C003               290.0          -55.0      235.0

In [4]:
# Create a column called Cumulative_Spend that shows the running total of Amount for each customer, ordered by Transaction_Date. 
# This means for each row, the value should be the sum of that customer's amounts from their first transaction up to and including that row.

df['Cumulative_Spend'] = df.groupby('Customer_ID')['Amount'].cumsum()
df

,Transaction_ID,Customer_ID,Transaction_Date,Amount,Category,Transaction_Type,Cumulative_Spend
0,1001,C001,2024-01-05,250.0,Electronics,Purchase,250.0
1,1002,C001,2024-01-12,75.0,Groceries,Purchase,325.0
2,1003,C002,2024-01-08,-50.0,Electronics,Return,-50.0
3,1004,C001,2024-01-20,300.0,Electronics,Purchase,625.0
4,1005,C003,2024-01-15,120.0,Clothing,Purchase,120.0
5,1006,C002,2024-01-22,200.0,Groceries,Purchase,150.0
6,1007,C003,2024-01-25,-30.0,Clothing,Return,90.0
7,1008,C001,2024-02-01,500.0,Electronics,Purchase,1125.0
8,1009,C002,2024-02-05,150.0,Electronics,Purchase,300.0
9,1010,C003,2024-02-10,80.0,Groceries,Purchase,170.0
10,1011,C001,2024-02-15,-100.0,Electronics,Return,1025.0
11,1012,C002,2024-02-18,175.0,Clothing,Purchase,475.0
12,1013,C003,2024-02-22,90.0,Clothing,Purchase,260.0
13,1014,C001,2024-02-28,425.0,Groceries,Purchase,1450.0
14,1015,C003,2024-03-01,-25.0,Electronics,Return,235.0

In [5]:
# Identify which customer has the highest single transaction amount and which customer has the most transactions overall. 
# Print both answers with labels.

maxamount = df.loc[df['Amount'].idxmax(), 'Customer_ID']
mosttransactions = df.groupby('Customer_ID')['Transaction_ID'].count().idxmax()

print(f"The most expensive transaction was from Customer ID: {maxamount} and the Customer ID with the most transactions was: {mosttransactions}.")

The most expensive transaction was from Customer ID: C001 and the Customer ID with the most transactions was: C001.